const life_of_budda = [
  { text: "THE LIFE OF THE BUDDHA", link: "/the-life-of-the-buddha/index.md" },
  { text: "THE LIFE OF THE BUDDHA", link: "/the-life-of-the-buddha/02-cover-02.md" },
  { text: "quote", link: "/the-life-of-the-buddha/03-cover-03.md" },
  { text: "Contents", link: "/the-life-of-the-buddha/04-content.md" },
  { text: "KEY TO ABBREVIATIONS", link: "/the-life-of-the-buddha/05-key-to-abbreviations.md" },
  { text: "EDITOR'S PREFACE", link: "/the-life-of-the-buddha/06-editor-s-preface.md" },
  { text: "NOTE TO THE THIRD EDITION", link: "/the-life-of-the-buddha/07-note-to-the-third-edition.md" },
  { text: "INTRODUCTION", link: "/the-life-of-the-buddha/08-introduction.md" },
  { text: "VOICES", link: "/the-life-of-the-buddha/09-voices.md" },
  { text: "1 THE BIRTH AND THE EARLY YEARS", link: "/the-life-of-the-buddha/10-1-the-birth-and-the-early-years.md" },
  { text: "2 THE STRUGGLE FOR ENLIGHTENMENT", link: "/the-life-of-the-buddha/11-2-the-struggle-for-enlightenment.md" },
  { text: "3 AFTER THE ENLIGHTENMENT", link: "/the-life-of-the-buddha/12-3-after-the-enlightenment.md" },
  { text: "4 THE SPREADING OF THE DHAMMA", link: "/the-life-of-the-buddha/13-4-the-spreading-of-the-dhamma.md" },
  { text: "5 THE TWO CHIEF DISCIPLES", link: "/the-life-of-the-buddha/14-5-the-two-chief-disciples.md" },
  { text: "6 ANĀTHAPIṆḌIKA", link: "/the-life-of-the-buddha/15-6-anathapindika.md" },
  { text: "7 FORMATION OF THE ORDER OF NUNS", link: "/the-life-of-the-buddha/16-7-formation-of-the-order-of-nuns.md" },
  { text: "8 THE QUARREL AT KOSAMBĪ", link: "/the-life-of-the-buddha/17-8-the-quarrel-at-kosambi.md" },
  { text: "9 THE END OF THE FIRST TWENTY YEARS", link: "/the-life-of-the-buddha/18-9-the-end-of-the-first-twenty-years.md" },
  { text: "10 THE MIDDLE PERIOD", link: "/the-life-of-the-buddha/19-10-the-middle-period.md" },
  { text: "11 THE PERSON", link: "/the-life-of-the-buddha/20-11-the-person.md" },
  { text: "12 The Doctrine", link: "/the-life-of-the-buddha/21-12-the-doctrine.md" },
  { text: "13 DEVADATTA", link: "/the-life-of-the-buddha/22-13-devadatta.md" },
  { text: "14 OLD AGE", link: "/the-life-of-the-buddha/23-14-old-age.md" },
  { text: "15 THE LAST YEAR", link: "/the-life-of-the-buddha/24-15-the-last-year.md" },
  { text: "16 THE FIRST COUNCIL", link: "/the-life-of-the-buddha/25-16-the-first-council.md" },
  { text: "LIST OF SOURCES", link: "/the-life-of-the-buddha/26-list-of-sources.md" },
  { text: "UDĀNA", link: "/the-life-of-the-buddha/27-udana.md" },
  { text: "INDEX", link: "/the-life-of-the-buddha/28-index-items.md" },
  { text: "ABOUT THE AUTHOR", link: "/the-life-of-the-buddha/29-about-the-author.md" },
  { text: "THE VISION OF DHAMMA", link: "/the-life-of-the-buddha/30-the-vision-of-dhamma.md" },
  { text: "THE NOBLE EIGHTFOLD PATH:", link: "/the-life-of-the-buddha/31-the-noble-eightfold-path.md" },
  { text: "A COMPREHENSIVE MANUAL OF ABHIDHAMMA", link: "/the-life-of-the-buddha/32-a-comprehensive-manual-of-abhidhamma.md" },
  { text: "ABOUT PARIYATTI", link: "/the-life-of-the-buddha/33-about-pariyatti.md" },
];
export default life_of_budda;
